source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => [
                'RCTImage',
                'RCTCameraRoll',
                'RCTNetwork',
                'RCTText',
                'RCTWebSocket',
                'RCTLinkingIOS',
                'RCTSettings',
                'RCTGeolocation',
                'RCTActionSheet'
             ],
             :path => '../node_modules/react-native'
